remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# ===== 网站标题（只显示在顶部导航栏和浏览器标签页） =====
title: nice stories
title_separator: "|"
name: nice stories

# ===== 网站描述 =====
description: 写小说的人
author: 郑好

# ===== 配色皮肤 =====
minimal_mistakes_skin: "air"

# ===== 侧边栏 =====
author_profile: true

# ===== 页脚版权信息（中文 + 英文） =====
footer:
  links:[]

# ===== 必要插件 =====
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
